# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# This file contains a template configuration file, which is typically
# placed as .hlint.yaml in the root of your project

# Specify additional command line arguments

- arguments:
    [ "--cross"
    , "--threads=0"
    ]

- ignore: {name: "Use camelCase"}
- ignore: {name: "Redundant as"}
- ignore: {name: "Redundant do"}
- ignore: {name: "Redundant return"}
- ignore: {name: "Redundant guard", whithin: "lrdrNameToTextAnn"}

- ignore: { name: 'Use :' }
- ignore: { name: Avoid lambda }
- ignore: { name: Eta reduce }
- ignore: { name: Move brackets to avoid $ }
- ignore: { name: Redundant <$> }
- ignore: { name: Redundant $ }
- ignore: { name: Redundant bang pattern }
- ignore: { name: Redundant bracket }
- ignore: { name: Redundant flip }
- ignore: { name: Redundant id }
- ignore: { name: Redundant if }
- ignore: { name: Redundant lambda }
- ignore: { name: Replace case with fromMaybe }
- ignore: { name: Unused LANGUAGE pragma }
- ignore: { name: Use <=< }
- ignore: { name: Use <$> }
- ignore: { name: Use all }
- ignore: { name: Use and }
- ignore: { name: Use any }
- ignore: { name: Use concatMap }
- ignore: { name: Use const }
- ignore: { name: Use elem }
- ignore: { name: Use elemIndex }
- ignore: { name: Use fewer imports }
- ignore: { name: Use fewer LANGUAGE pragmas }
- ignore: { name: Use first }
- ignore: { name: Use fromLeft }
- ignore: { name: Use getContents }
- ignore: { name: Use if }
- ignore: { name: Use isNothing }
- ignore: { name: Use lambda-case }
- ignore: { name: Use mapM }
- ignore: { name: Use minimumBy }
- ignore: { name: Use newtype instead of data }
- ignore: { name: Use record patterns }
- ignore: { name: Use second }
- ignore: { name: Use section }
- ignore: { name: Use sortOn }
- ignore: { name: Use sqrt }
- ignore: { name: Use tuple-section }
- ignore: { name: Use unless }
- ignore: { name: Use when }
