system-ghc: true
allow-newer: true
resolver: nightly-2021-11-06
extra-deps:
  - aeson-2.0.1.0
  - butcher-1.3.3.2
  - Cabal-3.6.2.0
  - data-tree-print-0.1.0.2
  - multistate-0.8.0.3
  - parsec-3.1.14.0
  - text-1.2.5.0
  - git: https://github.com/mithrandi/czipwith
    commit: b6245884ae83e00dd2b5261762549b37390179f8
